TOPIC_LIBRARY = {
    "Premier League": [
        "Golden Boot winners",
"Most assists in a season",
"Most appearances (player)",
"Clean sheet records (goalkeepers and teams)",
"Hat-tricks (most in a season/career)",
"Youngest and oldest players (debuts, goalscorers)",
"Relegation battles (teams relegated, dramatic escapes)",
"Managers with most matches",
"Longest unbeaten runs (single season, overall)",
"Biggest wins and losses (margin of victory)",
"Premier League champions (by year and by club)",
"Most points in a season (team record)",
"Most goals scored in a season (team record)",
"Fewest goals conceded in a season (team record)",
"Invincible season (Arsenal 2003-04)",
"Player of the Season award winners",
"Manager of the Season award winners",
"Golden Glove winners",
"Playmaker of the Season winners (most assists overall)",
"Most Premier League titles (player and manager)",
"Clubs ever-present in the Premier League",
"Memorable last-day title deciders",
"Iconic and controversial moments (e.g., Cantona's kung-fu kick, specific refereeing decisions)",
"Promoted teams' performance (highest finish, quick return to Championship)",
"Transfers (most expensive, impactful signings)",
"Stadiums (capacity, iconic grounds)",
"Derby matches (results, rivalries)",
"Team records (most wins, most draws, most losses in a season)",
"Individual scoring records (most goals in a single game, fastest goal)",
"Individual disciplinary records (most red cards, most yellow cards)",
"Impact of VAR (controversies, significant decisions)"

    ],
    "La Liga": [
"Pichichi Trophy winners (top scorers)",
"El Clásico results and historical head-to-head records",
"Barcelona and Real Madrid club records (most titles, longest winning streaks, points records, significant goal milestones)",
"Most assists in a season (individual record)",
"Notable transfers within La Liga (most expensive, most impactful, controversial moves)",
"Historic relegations and promotions (teams that have yo-yoed, surprising relegations/promotions)",
"Goalkeeper records (most clean sheets in a season/career, Zamora Trophy winners)",
"La Liga winning coaches (most titles, longest tenures)",
"Fastest goals in La Liga history",
"Most La Liga titles (club record, consecutive titles)",
"European successes of La Liga clubs (Champions League, Europa League winners from Spain)",
"Player appearances records (most games played in La Liga)",
"Iconic players and their records (e.g., Messi's goal and assist records, Ronaldo's goalscoring feats)",
"Stadiums and their history (iconic grounds, capacity changes)",
"Derby matches (other significant regional rivalries and their histories)",
"Financial fair play and its impact on La Liga clubs",
"Golden Boy award winners from La Liga clubs"
],

"Serie A": [
"Capocannoniere winners (top scorers by season)",
"Juventus title streaks and their historical dominance",
"Milan derby results (Derby della Madonnina) and historical head-to-head",
"Iconic defenders (e.g., Maldini, Baresi, Nesta, Cannavaro) and their achievements/records",
"Highest scoring matches in Serie A history",
"Club bankruptcies and returns (teams facing financial hardship, re-establishment, or significant comebacks)",
"Managers with most Serie A titles",
"Serie A stadium trivia (oldest stadiums, unique features, shared stadiums like San Siro/Stadio Olimpico)",
"Scudetto winners (by year and by club)",
"Longest unbeaten runs (club and individual player records)",
"Coppa Italia and Supercoppa Italiana winners (domestic cup achievements)",
"European successes of Serie A clubs (Champions League, UEFA Cup/Europa League, Cup Winners' Cup)",
"Most appearances (player record)",
"Individual disciplinary records (most red cards, most yellow cards)",
"Calciopoli scandal and its impact on the league",
"Youngest and oldest goalscorers/debutants"
],

"Bundesliga": [
"Torjägerkanone winners (top scorers by season)",
"Bayern Munich dominance (number of titles, consecutive titles, 'Rekordmeister' status, treble wins)",
"Longest unbeaten streaks (club records, home/away streaks)",
"Revierderby history (Borussia Dortmund vs. Schalke 04 results, major moments, fan culture)",
"Goalkeeping legends (e.g., Sepp Maier, Oliver Kahn, Manuel Neuer) and their records/awards",
"Most goals in a season (individual and team records)",
"Promotion and relegation stories (play-off history, teams that bounced back)",
"Youngest goal scorers in Bundesliga history",
"Bundesliga champions (by year and by club)",
"DFB-Pokal winners (domestic cup history)",
"European successes of Bundesliga clubs (Champions League, UEFA Cup/Europa League winners)",
"Average attendance records (Bundesliga's reputation for high attendance)",
"One-club men and loyal players (players who spent their entire careers at one Bundesliga club)",
"Managerial records (most games managed, most titles)",
"Goal of the Month/Season awards (iconic goals)",
"Fastest goal in Bundesliga history"
],

"Ligue 1": [
"PSG records (most Ligue 1 titles, domestic cup dominance, goalscoring records)",
"Top scorers (individual by season and all-time Ligue 1 top scorers)",
"Longest win streaks (club records in a single season or across seasons)",
"Goalkeeper clean sheet records (most clean sheets in a season/career)",
"Ligue 1 champions since 2000 (era of Lyon dominance, rise of PSG, other winners)",
"Historic Marseille achievements (Champions League win, domestic titles, fan culture)",
"Young talents who broke through (players who made their name in Ligue 1 before moving to bigger leagues)",
"Most Ligue 1 titles (club record, historical context beyond PSG)",
"Coupe de France and Coupe de la Ligue winners (domestic cup achievements)",
"European performances of Ligue 1 clubs (beyond Marseille's Champions League win)",
"Derby matches (other significant regional rivalries, e.g., Le Classique)",
"Player appearances records (most games played in Ligue 1)",
"Managerial records (most games managed, most titles)",
"Impact of financial investment (e.g., PSG's Qatari ownership, Monaco's investment)",
"Golden shoe winners from Ligue 1"
],
    "MLS": [ 
"MLS Cup winners (by year and by club, most successful teams)",
"Designated Players (DPs) and their impact (famous DPs, the 'Beckham Rule')",
"Top scorers in league history (all-time leading scorers, Golden Boot winners)",
"Goalkeeper of the Year winners (notable goalkeeping records)",
"Notable inter-conference rivalries (e.g., California Clásico, Cascadia Cup, 401 Derby, Atlantic Cup)",
"Expansion teams and performance (most successful expansion sides, challenges for new clubs)",
"Playoff format changes throughout MLS history",
"Supporters' Shield winners (regular season champions)",
"MLS MVP award winners",
"Most assists in MLS history (player records)",
"Longest unbeaten runs (club records)",
"Biggest wins and losses (margin of victory)",
"Coaching legends and their achievements in MLS",
"Attendance records and growth of the league",
"Stadiums (soccer-specific stadiums, multi-purpose venues)",
"MLS All-Star Game history and format"
],

"Rest of World": [
"Brazilian league champions (Série A winners, most successful clubs like Palmeiras, Flamengo)",
"Top scorers in Argentina's Primera División (all-time and recent Golden Boot winners)",
"K-League trivia (dominant clubs like Jeonbuk Hyundai Motors, Ulsan HD, unique league structure, fan culture)",
"J-League trivia (prominent clubs, impact on Asian football, notable players, unique formats)",
"A-League achievements (most Premiership/Championship titles, notable records for wins/appearances/goals, successful clubs like Sydney FC)",
"Most league titles in major African domestic leagues (e.g., Egyptian Premier League - Al Ahly/Zamalek, South African Premier Division - Mamelodi Sundowns/Kaizer Chiefs, Nigerian Professional Football League)",
"Continental treble winners outside Europe (clubs that have won their domestic league, domestic cup, and continental club competition, e.g., Al Ahly, Mazembe)",
"South American player development clubs (clubs renowned for producing top talent, e.g., River Plate, Boca Juniors, Santos, Ajax (Brazil))",
"Major league winners in Mexico (Liga MX champions, most titles for clubs like Club América, Guadalajara)",
"Popular players who stayed in their domestic leagues (icons of non-European leagues who achieved legendary status without major European careers)",
"Biggest rivalries in non-European leagues (e.g., Superclásico in Argentina (Boca Juniors vs. River Plate), El Clásico in Mexico (Club América vs. Guadalajara), Fla-Flu/Paulista Derby in Brazil, Cairo Derby in Egypt (Al Ahly vs. Zamalek), Donghaean Derby in K-League, F3 Derby in A-League)",
"Historical impacts of financial situations on non-European clubs (e.g., clubs facing bankruptcy, financial dominance of specific teams)",
"Significant transfers of players from non-European leagues to Europe (impact on talent drain)",
"Top club performances in continental competitions outside UEFA (e.g., Copa Libertadores, CAF Champions League, AFC Champions League winners)",
"Unique league formats or rules in different countries (e.g., Apertura/Clausura, split seasons, specific foreign player rules)",
"Stadiums and their atmospheres in prominent non-European leagues (e.g., La Bombonera, Maracanã)"
],
}
